### model
model_name_or_path: ../../model/chat_model/Qwen3-14B
trust_remote_code: true

### method
stage: sfl
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### sfl
sfl_score_tokens: "0,1"
sfl_prefix_str: '{"score": '
sfl_temperature: 5.0

### dataset
dataset: helpsteer3_multilingual_sfl_binary_train
eval_dataset: helpsteer3_sfl_binary_eval_multilingual
template: qwen3
enable_thinking: false
cutoff_len: 4096
preprocessing_num_workers: 16

### output
output_dir: /workspace/model/ckpt/reward_model/helpsteer3-sfl-multilingual-qwen3-14b-full-z3
run_name: helpsteer3_sfl_multilingual_qwen3_14b_full_z3
logging_steps: 10
save_steps: 200
save_strategy: steps
plot_loss: true
overwrite_output_dir: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: true
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 16
