### model
model_name_or_path: /workspace/model/chat_model/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: sfl
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: all

### sfl
sfl_score_tokens: "1,2,3,4,5"
sfl_prefix_str: '{"score": '
sfl_temperature: 2.0

### dataset
dataset: helpsteer2_sfl_1_5_train_upsample_correctness_anti
eval_dataset: helpsteer2_sfl_1_5_eval_tagged
template: qwen
cutoff_len: 4096
preprocessing_num_workers: 16

### output
output_dir: saves/helpsteer2/sfl-1-5-T2-lora_upsample_correctness_anti
run_name: helpsteer2_sfl_1_5_lora_r16_upsample_correctness_anti
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: true
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 16
